"""Canonical mapping between MorphHB OSIS and BHSA book names."""

BOOKS = (
    ("Gen", "Genesis"),
    ("Exod", "Exodus"),
    ("Lev", "Leviticus"),
    ("Num", "Numeri"),
    ("Deut", "Deuteronomium"),
    ("Josh", "Josua"),
    ("Judg", "Judices"),
    ("1Sam", "Samuel_I"),
    ("2Sam", "Samuel_II"),
    ("1Kgs", "Reges_I"),
    ("2Kgs", "Reges_II"),
    ("Isa", "Jesaia"),
    ("Jer", "Jeremia"),
    ("Ezek", "Ezechiel"),
    ("Hos", "Hosea"),
    ("Joel", "Joel"),
    ("Amos", "Amos"),
    ("Obad", "Obadia"),
    ("Jonah", "Jona"),
    ("Mic", "Micha"),
    ("Nah", "Nahum"),
    ("Hab", "Habakuk"),
    ("Zeph", "Zephania"),
    ("Hag", "Haggai"),
    ("Zech", "Sacharia"),
    ("Mal", "Maleachi"),
    ("Ps", "Psalmi"),
    ("Job", "Iob"),
    ("Prov", "Proverbia"),
    ("Ruth", "Ruth"),
    ("Song", "Canticum"),
    ("Eccl", "Ecclesiastes"),
    ("Lam", "Threni"),
    ("Esth", "Esther"),
    ("Dan", "Daniel"),
    ("Ezra", "Esra"),
    ("Neh", "Nehemia"),
    ("1Chr", "Chronica_I"),
    ("2Chr", "Chronica_II"),
)

OSIS_TO_BHSA = dict(BOOKS)
